/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#e3e2e2',
        'on-tertiary-fixed-variant': '#872000',
        'on-background': '#e5e2e1',
        surface: '#131313',
        'error-container': '#93000a',
        error: '#ffb4ab',
        background: '#131313',
        'outline-variant': '#3a494a',
        tertiary: '#fff9f7',
        'on-secondary-fixed-variant': '#464747',
        'on-error': '#690005',
        'surface-container-highest': '#353534',
        'surface-container-high': '#2a2a2a',
        'inverse-primary': '#00696e',
        'tertiary-fixed': '#ffdbd1',
        'on-tertiary-container': '#b62f00',
        primary: '#e9feff',
        'primary-container': '#00f5ff',
        'on-secondary': '#2f3131',
        'on-primary-container': '#006c71',
        'secondary-container': '#484949',
        'on-tertiary-fixed': '#3b0900',
        'on-surface-variant': '#b9caca',
        'surface-container-lowest': '#0e0e0e',
        'tertiary-container': '#ffd4c9',
        'on-primary': '#003739',
        'inverse-on-surface': '#313030',
        'surface-container': '#201f1f',
        'inverse-surface': '#e5e2e1',
        'surface-tint': '#00dce5',
        'surface-container-low': '#1c1b1b',
        'on-primary-fixed': '#002021',
        outline: '#849495',
        'surface-bright': '#3a3939',
        'primary-fixed': '#63f7ff',
        'surface-variant': '#353534',
        'secondary-fixed-dim': '#c7c6c6',
        'on-secondary-container': '#b8b8b8',
        'surface-dim': '#131313',
        'on-surface': '#e5e2e1',
        'on-primary-fixed-variant': '#004f53',
        'on-secondary-fixed': '#1a1c1c',
        secondary: '#c7c6c6',
        'tertiary-fixed-dim': '#ffb5a0',
        'on-tertiary': '#601400',
        'on-error-container': '#ffdad6',
        'primary-fixed-dim': '#00dce5',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['"Space Grotesk"', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
